### ISSUE TITLE
Ordering of nodes after insert-child() don't reflect insertion order

### ISSUE THREAD

**Issue by tademianhess** [ryanjdew/XQuery-XML-Memory-Operations#16]
I am probably misusing the library, so hope you can clarify the correct usage.

The example code moves children from one element and inserts them into another. Each time the code runs in qconsole (ML v8.0-5), the ordering of the inserted children changes. I would like the ordering of the nodes to be consistent and reflect the order of insertion (one, two, three, etc.).

```
xquery version "1.0-ml";
import module namespace mem = "http://maxdewpoint.blogspot.com/memory-operations/functional" 
   at "memory-operations-functional.xqy";
let $x := <root><original-container><one/><two/><three/><four/><five/></original-container><new-container/></root>
let $tx := mem:copy($x)
let $_ :=
   for $item in $x/original-container/*
   return ( 
     xdmp:set($tx, mem:delete($tx, $item) ), 
     xdmp:set($tx, mem:insert-child($tx, $x/new-container, $item))
   )
return mem:execute( $tx )
```
This emulates an xquery module I am refactoring that restructures an XML document. I wanted to start a single transaction, make the updates, and then invoke mem:execute() at the end to replace the original document in MarkLogic.

As you can see, I am invoking the mem:delete(), mem:insert-child(), etc. operations and then using xdmp:set() to update the original transaction map. Perhaps this isn't the correct usage and is causing the problem?

**Comment by ryanjdew** [comment]
Thanks for filing an issue and catching this bug.

There was a bug with a set of expressions that was causing the multiple nodes to be returned in "document order", which when the nodes are across different documents can seem pretty random. If you pull down the latest, the issue should be resolved. 

The unit tests I have missed that, since in my "ideal" unit tests all operations of one type on a node were submitted at the same time.

Also, in your code snippet, the xdmp:set is unnecessary. So the following should work for you:
```xquery
xquery version "1.0-ml";
import module namespace mem = "http://maxdewpoint.blogspot.com/memory-operations/functional" 
   at "memory-operations-functional.xqy";
let $x := <root><original-container><one/><two/><three/><four/><five/></original-container><new-container/></root>
let $tx := mem:copy($x)
let $_ :=
   for $item in $x/original-container/*
   return ( 
     mem:delete($tx, $item), 
     mem:insert-child($tx, $x/new-container, $item)
   )
return mem:execute( $tx )
```

**Comment by tademianhess** [comment]
Thanks, that does fix the ordering.

For some reason, I still need to call xdmp:set(). If I run the code you provided in QConsole, the changes are not reflected in the output:

```xml
<root>
    <original-container>
       <one/><two/><three/><four/><five/>
    </original-container>
    <new-container/>
</root>

```
But running with xdmp:set():
``` xml
<root>
    <original-container/>
    <new-container>
        <one/><two/><three/><four/><five/>
    </new-container>
</root>
```
